version: "3.8"
services:
  backend:
    container_name: mrdang-backend
    image: mrdang
    restart: always
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8082:8080
    networks:
      - mrdang-net

  database:
    container_name: mrdang-db
    image: mysql:8.3.0
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
      MYSQL_DATABASE: ${DATABASE_NAME} 
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 20s
      retries: 30
    networks:
      - mrdang-net
    
networks:
  mrdang-net:
    driver: bridge