spring:
  application:
    name: "mrdang-test"

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  auth:
    jwt:
      secretKey: testsecretkeytestsecretkeytestsecretkeytestsecretkeytestsecretkeytestsecretkey
      refreshTokenExpiry: 36000000
      accessTokenExpiry: 1800000

server:
  port: 8081