spring:
  # JPA 세팅
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #  DB 세팅 dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5

  auth:
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      refreshTokenExpiry: 36000000 # 10시간
      accessTokenExpiry: 1800000 # 30분


file:
  root-location: "/attach"

sso:
  host: ${SSO_HOST}
  port: ${SSO_PORT}
  api:
    key: ${SSO_API_KEY}
  retUrl: ${SSO_RETURL_DEV}

# Logging 세팅
# TODO: 제거
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE